Repository AndreasReitberger/OctoPrintRestApiSharp, pull requests merged in 2022-12, with the labels that each got.

#7 Refactor/implement observable properties
  .gitignore
  source/OctoPrintSharpApi/OctoPrintClient.cs
  source/OctoPrintSharpApi/OctoPrintConnectionBuilder.cs
  source/OctoPrintSharpApi/OctoPrintSharpApi.csproj
Labels: enhancement, net7

#8 Feature/add .net 7 framework support
  source/OctoPrintSharpApi/OctoPrintSharpApi.csproj
Labels: enhancement, net7

#10 Removed old PropertyChanged event from `OctoPrintClient` class
  source/OctoPrintSharpApi/Interfaces/IPrintServerClient.cs
  source/OctoPrintSharpApi/OctoPrintClient.Static.cs
  source/OctoPrintSharpApi/OctoPrintClient.cs
  source/OctoPrintSharpApi/OctoPrintConnectionBuilder.cs
  source/OctoPrintSharpApi/OctoPrintSharpApi.csproj
  source/OctoPrintSharpApiTest/OctoPrintSharpApiTest.csproj
Labels: bug, net7

#12 Workaround for serialisation issues
  source/OctoPrintSharpApi.NUnitTest/NUnitTests.cs
  source/OctoPrintSharpApi.NUnitTest/OctoPrintSharpApi.NUnitTest.csproj
  source/OctoPrintSharpApi.NUnitTest/Usings.cs
  source/OctoPrintSharpApi.sln
  source/OctoPrintSharpApi/OctoPrintClient.cs
  source/OctoPrintSharpApiTest/OctoPrintSharpApiTest.csproj
Labels: bug, net7, dependency

#14 Project cleanup
  source/OctoPrintSharpApi/OctoPrintClient.cs
  source/OctoPrintSharpApi/OctoPrintSharpApi.csproj
Labels: documentation, net7

#15 Fixed spelling mistakes.
  source/OctoPrintSharpApi/Enum/OctoPrintConnectionStates.cs
  source/OctoPrintSharpApi/Enum/OctoPrintDefaultGroup.cs
  source/OctoPrintSharpApi/Models/Events/OctoPrintEventArgs.cs
  source/OctoPrintSharpApi/Models/Events/OctoPrintEventSessionChangedEventArgs.cs
  source/OctoPrintSharpApi/Models/Files/OctoPrintUploadFileResponse.cs
  source/OctoPrintSharpApi/Models/Result/OctoPrintApiRequestRespone.cs
  source/OctoPrintSharpApi/Models/WebSocket/OctoPrintWebSocketConnectionResponse.cs
  source/OctoPrintSharpApi/OctoPrintClient.Static.cs
  source/OctoPrintSharpApi/OctoPrintClient.cs
Labels: t/housekeeping ♻︎
